### ISSUE TITLE
Package not in NPM registry 

### ISSUE THREAD

**Issue by johntdyer** [michaelansel/hubot-rate-limit#1]
Hello, 

 Your installation instructions say to run `npm install hubot-rate-limit --save` however this fails because this package is not published in the registry.  

Thanks
-John

**Comment by michaelansel** [comment]
Yup, I'm waiting for github/hubot#803 to merge before I release this module. I want to be able to specify a proper peerDependency before publishing.

**Comment by michaelansel** [comment]
Should be all set!
