### ISSUE TITLE
installation requirements appear to be missing

### ISSUE THREAD

**Issue by johntdyer** [michaelansel/hubot-rate-limit#2]
Based on the following error message I believe this package depends on https://github.com/github/hubot/pull/803 being merged in.  

```
/var/log/hubot.out:[Mon Dec 15 2014 09:07:44 GMT-0500 (EST)] ERROR Unable to load /opt/hubot/node_modules/hubot-rate-limit/src/rate-limit: TypeError: Object #<Robot> has no method 'listenerMiddleware'
```

If this is correct perhaps that requirement should be listed in the readme ? 

Thanks

**Comment by michaelansel** [comment]
Correct, this is dependent on middleware. I'm waiting for that to merge before I release the rate limiting module.

**Comment by michaelansel** [comment]
Now that github/hubot#803 has been released, everything should be working
